// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);


            modelBuilder.Entity("WebApi.Entities.Witness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<int>("PollingStationID");

                    b.Property<int?>("UploadedBy");

                    b.Property<string>("UploadedTime");

                    b.Property<string>("WilayatCode");

                    b.HasKey("Id");

                    b.HasIndex("PollingStationID");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("WilayatCode");

                    b.ToTable("Witness");
                });

            modelBuilder.Entity("WebApi.Entities.Witness", b =>
                {
                    b.HasOne("WebApi.Entities.PollingStations", "PollingStation")
                        .WithMany()
                        .HasForeignKey("PollingStationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Entities.User", "uploadedByMember")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.HasOne("WebApi.Entities.Wilayats", "Wilayat")
                        .WithMany()
                        .HasForeignKey("WilayatCode");
                });
#pragma warning restore 612, 618
        }
    }
}
